remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Dr. G. Brückmann]
description: [Postdoctoral researcher studying environmental policies 🌍 & experiments 🎲, currently based in London.]
description: [ [Email](mailto:gracia.brueckmann@unibe.ch) / [Website](https://www.ipw.unibe.ch/about_us/people/dr_brueckmann_gracia/index_eng.html) / [ORCID](https://orcid.org/0000-0001-5674-2343) / [Google Scholar](https://scholar.google.ch/citations?user=CrgXLfIAAAAJ&hl=en/) / [GitHub](https://github.com/brueckmann/) / [Fediverse](https://fediscience.org/@brueckmann/) / [Bluesky](https://bsky.app/profile/brueckmann.bsky.social/) / [Twitter](https://twitter.com/gbrueckmann/) ]
