project:
  type: website
  output-dir: docs


website:
  title: "G. Brückmann"
  favicon: test2.svg
  description: "Postdoctoral Researcher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: "Academic CV"
      - href: publications.qmd
        text: "Publications"
      - href: projects.qmd
        text: "Research Projects"
      - href: teaching.qmd
        text: "Teaching"
      - href: contact.qmd
        text: "Contact Me"
  page-footer: 
    left: "G. Brückmann, 2025." 
    right: 
      - icon: github
        href: https://github.com/brueckmann/brueckmann.github.io
  back-to-top-navigation: true   

format:
  html:
    respect-user-color-scheme: true
    theme:
       solar
    css: styles.css
    toc: true
    toc-depth: 2



