project:
  type: website
  output-dir: docs


website:
  title: "G. Brückmann"
  description: "Postdoctoral Researcher"
  page-footer: 
    left: "G. Brückmann, 2025." 
    right: 
      - icon: github
        href: https://github.com/brueckmann/
  back-to-top-navigation: true      
  favicon: <i class="bi bi-lightning-charge-fill"></i>
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: "Academic CV"
 

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: solar
      dark: solar
    css: styles.css
    toc: true
    toc-depth: 2



