---
title:  ""
engine: knitr
freeze: false
---
 
 ```{=html}
  <p class="text-center">
 <a href="mailto:gracia.brueckmann@unibe.ch"><i class="bi bi-send-plus"></i></i>Email</a> / 
 <a href="https://www.ipw.unibe.ch/about_us/people/dr_brueckmann_gracia/index_eng.html"><i class="bi bi-briefcase-fill"></i>Institute</a> / 
 <a href="https://orcid.org/0000-0001-5674-2343"><i class="ai ai-orcid"></i>ORCID</a> / 
 <a href="https://scholar.google.ch/citations?user=CrgXLfIAAAAJ&amp;hl=en/"><i class="ai ai-google-scholar"></i>Google Scholar</a> / 
 <a href="https://osf.io/rbnhe/"><i class="ai ai-osf"></i>OSF</a> / 
 <a href="https://github.com/brueckmann/"><i class="bi bi-github"></i>GitHub</a> / 
 <a href="https://fediscience.org/@brueckmann/"><i class="bi bi-mastodon"></i>Fediverse</a> / 
 <a href="https://bsky.app/profile/brueckmann.bsky.social/"><i class="bi bi-bluesky"></i>Bluesky</a> <br><br>
</p>
```

## 🧑🏼‍💻 Current Position 

**Post-Doc | University of Bern** @ [Institute of Political  Science](https://www.ipw.unibe.ch/) & [Oeschger Centre for Climate Change Research](https://www.oeschger.unibe.ch/) <br> _(10/2021 to Present)_ <br>
Working on the projects [SWEET EDGE](https://www.sweet-edge.ch/en/home/) (Enabling Decentralized renewable GEneration in the Swiss cities, midlands, and the Alps) focussing on solar PV policy acceptance, and [SURE](https://sweet-sure.ch/) (SUstainable and Resilient Energy for Switzerland) with focus on future climate and energy policy, both funded by Swiss Federal Office of Energy, [SFOE](https://www.bfe.admin.ch/bfe/en/home/research-and-cleantech/funding-program-sweet.html/). [Teaching](#own-semester-long-teaching) and organisation of the [Swiss Social Science & Humanities Energy Research Group](https://t1p.de/SSHEnergy). 
<br><br>

## 🚗 Previous Academic Positions 

**Visiting Fellow | London School of Economics and Political Science** @ [Social Policy Department](https://www.lse.ac.uk/social-policy/) <br> _(09/2023-12/2023)_ <br>
Working on urban experiences with environmental policies targeted at transport emissions, such as Low Traffic Neighbourhoods  (LTNs) and Ultra-Low Emission Zones (ULEZ).<br><br>

**Researcher & PhD Candidate | ETH Zurich** @ [International Political Economy and Environmental Politics](https://ib.ethz.ch/) & [Institute of Science, Technology and Policy](https://istp.ethz.ch/) [(Swiss Mobility Lab)](https://istp.ethz.ch/research/mobility.html) <br>
_(10/2017-09/2021)_	<br>
Projects included e.g., [Fostering the Transition Towards More Fuel-Efficient Cars](https://www.aramis.admin.ch/Texte/?ProjectID=41021&Sprache=en-US) funded by Swiss Federal Office of Energy, [SFOE](https://www.bfe.admin.ch/bfe/en/home/research-and-cleantech/research-programmes/energy-economy-society-ees.html/).
<br><br>

## 🎓 Completed Education

**Dr. sc. ETH**, Doctoral thesis entitled [_Electric vehicle adoption and acceptance_](https://www.research-collection.ethz.ch/handle/20.500.11850/512355). <br>
[ETH Zurich](https://ethz.ch/en.html), Switzerland. <br>
Supervisor: Thomas Bernauer Committee members: Isabelle Stadelmann-Steffen, Kay W. Axhausen. _(2017– 2021)_	
<br>

**Master of Science**, International Economics and Policy Consulting <br>[University of Magdeburg](https://www.ovgu.de/en/), Germany. <br>
Thesis: _An Econometric Analysis of the Effect of Political Contributions from the Oil Industry on Votes at the US Congress_. _(2014 – 2017)_	
<br>

**Exchange Semester**, [University of Nice](https://univ-cotedazur.eu/) Sophia Antipolis, France. _(2015 - 2016)_	<br>

**Bachelor of Science**, Economics  <br>[University of Munich](https://www.lmu.de/en/index.html), Germany. <br>
Thesis: _Widowhood, Medical Expenditures, and Health Care Utilization among the Elderly US Population_. _(2010 – 2013)_	
<br>

**Exchange Semester**, [Stockholm University](https://www.su.se/english/), Sweden. _(2012 - 2013)_
<br><br>

## 📑 Publications
### 📔 Peer-reviewed Publications in Academic Journals

Brückmann, G. (2025). _Public opinion on climate policies that reduce emissions abroad to reach domestic targets - a Swiss case study_. Current Research in Environmental Sustainability, 10, 100295. [doi.org/10.1016/j.crsust.2025.100295](https://doi.org/10.1016/j.crsust.2025.100295)<br>

Brückmann, G., Ruprecht, S., & Stadelmann-Steffen, I. (2024). _Solar for tenants: Survey evidence on design and framing of citizen-financed photovoltaic projects in Switzerland_. Energy Research & Social Science, 118, 103819. [/doi.org/10.1016/j.erss.2024.103819](https://doi.org/10.1016/j.erss.2024.103819) <br>

Brückmann, G. & Bernauer, T. (2023). _An experimental analysis of consumer preferences towards public charging infrastructure_. Transportation Research Part D: Transport and Environment, 116, 103626. [doi.org/10.1016/j.trd.2023.103626](https://doi.org/10.1016/j.trd.2023.103626) <br>

Brückmann, G., Berger, S., Caviola, H., Hahnel, U., Piana, V., Sahakian M., Stadelmann-Steffen, I. & the Swiss Social Science and Humanities Energy Research Group (2023). _Towards more impactful energy research: The salient role of social sciences and humanities_. PLOS Climate, 2(2), [doi.org/10.1371/journal.pclm.0000132](https://doi.org/10.1371/journal.pclm.0000132) <br>
• Covered in [energeia](https://energeiaplus.com/2023/02/22/krisen-sprache-gerechtigkeit-was-hat-das-mit-energieforschung-zu-tun/).<br>

Brückmann, G. (2022). _The effects of policies providing information and trialling on the knowledge about and the intention to adopt new energy technologies_. Energy Policy, 167, [doi.org/10.1016/j.enpol.2022.113047](https://doi.org/10.1016/j.enpol.2022.113047) <br>

Brückmann, G. (2022). _Test drives & information might not boost actual battery electric vehicle uptake_. Transportation Research Part A: Policy and Practice, 160, [doi.org/10.1016/J.TRA.2022.03.025](https://doi.org/10.1016/J.TRA.2022.03.025) <br>

Wicki, M., Brückmann, G. & Bernauer, T. (2022). _How to accelerate the uptake of electric cars? Insights from a choice experiment_. Journal of Cleaner Production, [doi.org/10.1016/j.jclepro.2022.131774](https://doi.org/10.1016/j.jclepro.2022.131774) <br>

Wicki, M., Brückmann, G., Quoß, F. & Bernauer, T. (2022). _What do we really know about the acceptance of battery electric vehicles? – Turns out, not much_. Transport Reviews, [doi.org/10.1080/01441647.2021.2023693](https://doi.org/10.1080/01441647.2021.2023693) <br>

Brückmann, G., Wicki, M. & Bernauer, T. (2021). _Is resale anxiety an obstacle to electric vehicle adoption? Results from a survey experiment in Switzerland_. Environmental Research Letters, 16 (12), 124027. [doi.org/10.1088/1748-9326/ac3531](https://doi.org/10.1088/1748-9326/ac3531) <br>

Brückmann, G., Willibald, F. & Blanco, V. (2021). _Battery Electric Vehicle adoption in regions without strong policies_. Transportation Research Part D: Transport and Environment, 90, 102615. [doi.org/10.1016/J.TRD.2020.102615](https://doi.org/10.1016/J.TRD.2020.102615) <br>

Brückmann, G. & Bernauer, T. (2020). _What drives public support for policies to enhance electric vehicle adoption?_ Environmental Research Letters, 15(9), 094002. [doi.org/10.1088/1748-9326/ab90a5](https://doi.org/10.1088/1748-9326/ab90a5) <br>
• Covered in [Yale Environmental Review](https://environment-review.yale.edu/pulling-public-embrace-adoption-electric-vehicles). Explained in [ISTP4Public video](https://twitter.com/istp_eth/status/1271004682979336193?s=20). <br><br>

### 📝 Working Papers on Preprint Servers

Brückmann, G. & Stadelmann-Steffen, I. (2025). _To abstain or not to abstain from binary choice in conjoint experiments_. SocArXiv preprint. [https://www.doi.org/10.31235/osf.io/kr64j_v1](https://www.doi.org/10.31235/osf.io/kr64j_v1) <br>

Simpson, T., Jones, S., Brückmann, G., El-Ajou W., Moreira E., Martinez Oltra, B., Krause, R., Multerer, M., & Stadelmann-Steffen, I. (2025). _Ensured Energy: A simulation game to elicit preferences around Swiss energy transition pathways_. arXiv preprint. [https://doi.org/10.48550/arXiv.2508.12799](https://doi.org/10.48550/arXiv.2508.12799) <br>
•	Play [Ensured Energy](www.sweet-sure.ch/game), the _[Serious Game](https://github.com/brueckmann/CEGames)_ underlying this research. <br>

## 🧑🏼‍💼 Conference & Academic Seminar Presentations
* _2025_: SPSA (Swiss Political Science Association Annual Congress), Alp-Pop, MZES-DVPW Conference Methods of Political Science, PolMeth Europe, EPG Survey Workshop, Swiss Social Science and Humanities Energy Workshop <br>
* _2024_: SPSA, APSA (American Political Science Association) Virtual Research Meeting, Swiss Social Science and Humanities Energy Workshop, EPSA (European Political Science Association Annual Congress), E4EE (Workshop on Experimental Economics for the Environment) <br>
* _2023_: SPSA , EPCS (European Public Choice Society), EPSA, Swiss Social Science and Humanities Energy Workshop (as organizer and presenter), Dreiländertagung (D-A-CH-Congress) (presenter and panel organizer), LSE Social Policy seminar <br>
* _2022_: SPSA, PolMeth Europe, Swiss Social Science and Humanities Energy Workshops (lead organiser), EPSA, EPG Online  <br>
* _2021_: SPSA, OSWEET (Online Summer Workshop in Environment, Energy, and Transportation), Environment, Transport, and Sustainability (EnTS) Research Group Seminar University of Bath <br>
* _2020_: EMEE, SPSA (accepted, not participated due to injury.), PSA ECN, 3-Länder International Political Economy conference 2020. (Paper accepted, conference cancelled.)
* _2019_: IAEE International Conference, EPSA, AIEE Energy Symposium <br>

## 🧑🏼‍🏫 Teaching Experience

### Own semester-long teaching
* **Lecture**  _The Art of Causal Inference_, University of Bern _(Spring 2024)_ [Syllabus online](https://brueckmann.github.io/KKI_Syllabus/PDF_Syllabus_KKI_GBrueckmann.pdf) <br>
* **Master Seminar** _Energy and Mobility Policies for Decarbonisation_, University of Bern _(Fall 2022,2023,2024 & 2025)_ [Syllabus online](https://github.com/brueckmann/Syllabus_PolDec_HS2025/blob/main/PDF_Syllabus_PolDec_GBrueckmann.pdf) <br>
* **Tutorial** _Mathematical Methods in Economics_, accompanying  lecture by Prof. H. Rainer, Ph.D., LMU Munich _(2012)_ <br>

### Co-teaching, shorter teaching & thesis supervision
* **Lectures** _Renewable Energy Acceptance using Causality and Data Science_ Organiser: Prof. Dr. Philipp Schütz, Domain Experience: Data analytics for energy systems and IOT, Lucerne University of Applied Sciences and Arts. _(Spring 2024)_<br> 
* **Lectures** _Political Economy of Climate Change_, Organiser: Prof. Dr. V. Koubi, University of Bern _(Spring 2023)_<br> 
* **Lecture** _Climate Change Policy and Electric Vehicles in Europe_, Organiser: Climate Physics seminar, Weber State University, Ogden, Utah. _(Nov 2022)_<br>
* **Supervision** of _master thesis_ entiteled "Electric charging behaviour – Understanding the trilemma of willingness to pay, the value of time and source of energy in the context of public charging stations in the German part of Switzerland", ETH Zürich _(Nov 2021)_<br>
* **Lecture** on _Battery-electric Vehicle Adoption_ at Frontiers in Energy Research, Organiser: Energy Science Centre, ETH Zurich _(2021)_<br>
* **Lecture** on _Sustainable Development_ at “Political Economy”. Organisation jointly with: V. Koubi, D. Kolcava, ETH Zurich _(2021)_<br>
* **Supervision** of _master thesis_ entiteled “The role of charging infrastructure to the mainstream adoption of battery electric vehicles (BEVs)”, ETH Zurich _(2020)_<br>
* **Lecture** on _Experimental Political Science_ at Proseminar 2. Organisers: D. Presberger, F. Quoß, ETH Zurich _(2020)_<br>
* **Tutorial** _Methoden der Empirischen Sozialforschung_ (Empirical social science methods), lecture by Dr. L. Rudolph, ETH Zurich _(2018&2019)_<br>
* **Seminar** instructor _IDEA League Challenge: The mobility challenge_, Organize: Prof. Dr. T. Bernauer, ETH Zurich _(2018&2019)_<br>


## 💸 Grants
* **In-kind Grant** [University of Bern, Faculty of Business, Economics and Social Sciences, Competitive funding scheme for young researchers with outstanding scientific qualifications](https://www.wiso.unibe.ch/ueber_uns/gleichstellung_und_nachwuchsfoerderung/foerdermassnahmen/kompetitives_foerdergefaess_fuer_nachwuchsforschende_mit_herausragender_wissenschaftlicher_qualifizierung/index_ger.html) funding a research assistant for 8 months in 2025<br>
* **In-kind Grant** [University of Bern eCoaches digital skills in teaching program](https://www.ecoach.unibe.ch) funding a teaching assistant for Master's seminar in fall semester 2024<br>
* **Travel Grant** [UniBE Short Travel Grants for (Post)Docs](https://www.unibe.ch/studies/programs/doctorate/doctoral_degree/funding_program_unibe_short_travel_grants_for_postdocs/index_eng.html) funding for research stay at LSE, CHF 7,000, 2023<br>
* **Travel Grant** from Berne University Research Foundation for research stay at LSE, CHF 3,398, 2023<br>
* **Travel Grant** from Swiss Academy of Social Sciences and Humanities [(SAGW)](https://www.sagw.ch/sagw/) for a conference visit, CHF 500, 2023 <br>
* **Project Grant** Swiss Academy of Social Sciences and Humanities [(SAGW)](https://www.sagw.ch/sagw/), project funding for Swiss Social Science & Humanities Energy Research Group, CHF 7,000, 2022<br>
* **Project Grant**	Swiss Office of Energy Swiss Federal Office of Energy, [(SFOE)](https://www.bfe.admin.ch/), project funding for Swiss Social Science & Humanities Energy Research Group, CHF 5,000, 2022<br>
* **Project Grant** [Promotion Fund](https://www.unibe.ch/research/promotion_of_research/uni_internal_grants/promotion_fund/index_eng.html) (funding for networking activities of intermediate statt members) at University of Bern, project funding for Swiss Social Science and Humanities Energy Research Group Workshops, CHF 5,000, jointly received with Rebeka Sträter and Jonas Schmid<br>

## 🤝 Services to the community
* _Since 2025_:  EPSS (European Political Science Society) [Diversity Committee](https://epssnet.org/about/diversity-committee/).
* _Since 2024_:  Early Career Researcher (ECR) [Editorial Advisory Board Policy & Politics](https://bristoluniversitypressdigital.com/view/journals/pp/pp-overview.xml?tab_body=editorial-board).
* _Since 2022_:  Organizer [Swiss Social Science & Humanities Energy Research Group](https://www.ipw.unibe.ch/research/swiss_social_sciences__humanities_energy_research_group/index_eng.html/) <br>
* _Since 2022_:   Member of Commission for the Promotion of Early Career Researchers, University of Bern.<br>
* _Since 2022_:   Deputy Member Commission for Quality Assurance and Development and Gender Equality Commission, University of Bern.<br>
* _Since 2022_:   Head and Member of the panel for _The Fund for the Promotion of Young Researchers_, University of Bern.<br>
* _2019-2022_:	  Founding Member [MeWell Community](https://mewellcommunity.ch), Zurich. <br>
* _2017-2021_:	  Member of Commission for Master in Science, Technology and Policy (MSc ETH STP), ETH Zurich.<br>
* _2011-2012_:	  Student representative, Senate, LMU Munich. <br>

## 🌐 Memberships in Professional Networks
* [CSSN](https://cssn.org/scholar/g-bruckmann/) (Climate Social Science Network)
* [EPG](https://epgnetwork.org/) (Environmental Politics and Governance)
* [EPSS](https://epssnet.org/) (European Political Science Society)
* [saguf](https://saguf.ch/en) (Swiss Academic Society for Environmental Research and Ecology)
* [SwissRN](https://www.swissrn.org/contents/academy/#GraciaBr%C3%BCckmann) (Swiss Reproducibility Network Academy)
* [SPSA](https://www.svpw-assp.ch/) (Swiss Political Science Association)
* [Swiss Social Science & Humanities Energy Research Group](https://t1p.de/SSHEnergy)
* Relevant Standing Groups: [ECPR](https://ecpr.eu) (European Consortium for Political Research)
* [Queer UniBe](https://www.unibe.ch/university/portrait/self_image/equal_opportunities/topics/respectful_and_inclusive_study_and_work_environment/lgbtiq/network_queer_unibe/index_eng.html) & [ISNBS](https://isnbs.org/) 


## 🙇🏼 Peer-Review for Scientific Journals 
Applied Economics, Climate Policy, Energy Economics, Energy Policy, Energy Research & Social Science, Environmental Research Communications, Environmental Research Letters, Environmental Sciences Europe, European Journal of Political Research, Global Sustainability, Joule, Nature Energy, Patterns, PLOS Climate, Scientific Reports, The Journal of Politics, Transportation, Transportation Research Part D.
<br>

## 💬 Languages
🇩🇪 **German**: Native <br>
🇬🇧 **English**: C1 <br>
🇫🇷 **French**: B2 <br>
Some knowledge: 🇸🇪🇪🇸🇨🇭

