---
title: "Academic Publications"
format: html
date: last-modified
published-title: "Publications last updated:"
---

::: {.callout-tip collapse="false"}
#### Info
 ```{=html}
  <p class="text-center">
Find my published work also on <a href="https://orcid.org/0000-0001-5674-2343"><i class="ai ai-orcid"></i>ORCID</a> and
 <a href="https://scholar.google.ch/citations?user=CrgXLfIAAAAJ&amp;hl=en/"><i class="ai ai-google-scholar"></i>Google Scholar</a>.
</p>
```
:::




## 📝 Working Papers on Preprint Servers

Brückmann, G. & Stadelmann-Steffen, I. (2025). *To abstain or not to abstain from binary choice in conjoint experiments*. SocArXiv preprint. <https://www.doi.org/10.31235/osf.io/kr64j_v1> <br>

Simpson, T., Jones, S., Brückmann, G., El-Ajou W., Moreira E., Martinez Oltra, B., Krause, R., Multerer, M., & Stadelmann-Steffen, I. (2025). *Ensured Energy: A simulation game to elicit preferences around Swiss energy transition pathways*. arXiv preprint. <https://doi.org/10.48550/arXiv.2508.12799> <br> • Play [Ensured Energy](www.sweet-sure.ch/game), the [*Serious Game*](https://github.com/brueckmann/CEGames) underlying this research. <br>



::: {.callout-tip collapse="false"}
#### Upcoming work
```{=html}
<p>
For work-in-progress see my <a href="https://brueckmann.github.io/cv.html">CV</a>, the associated pre-registrations on <a href="https://osf.io/rbnhe/"><i class="ai ai-osf"></i>OSF</a> or head over to the <a href="https://brueckmann.github.io/projects.html">projects page</a>.
</p>
```
:::

## 📔 Peer-reviewed Journal Publications

Brückmann, G. (2025). *Public opinion on climate policies that reduce emissions abroad to reach domestic targets - a Swiss case study*. Current Research in Environmental Sustainability, 10, 100295. [doi.org/10.1016/j.crsust.2025.100295](https://doi.org/10.1016/j.crsust.2025.100295)<br> • Covered in [SWEET EDGE video](https://youtu.be/_LJ9XbShaVk?feature=shared).<br>

Brückmann, G., Ruprecht, S., & Stadelmann-Steffen, I. (2024). *Solar for tenants: Survey evidence on design and framing of citizen-financed photovoltaic projects in Switzerland*. Energy Research & Social Science, 118, 103819. [/doi.org/10.1016/j.erss.2024.103819](https://doi.org/10.1016/j.erss.2024.103819) <br>

Brückmann, G. & Bernauer, T. (2023). *An experimental analysis of consumer preferences towards public charging infrastructure*. Transportation Research Part D: Transport and Environment, 116, 103626. [doi.org/10.1016/j.trd.2023.103626](https://doi.org/10.1016/j.trd.2023.103626) <br>

Brückmann, G., Berger, S., Caviola, H., Hahnel, U., Piana, V., Sahakian M., Stadelmann-Steffen, I. & the Swiss Social Science and Humanities Energy Research Group (2023). *Towards more impactful energy research: The salient role of social sciences and humanities*. PLOS Climate, 2(2), [doi.org/10.1371/journal.pclm.0000132](https://doi.org/10.1371/journal.pclm.0000132) <br> • Covered in [energeia](https://energeiaplus.com/2023/02/22/krisen-sprache-gerechtigkeit-was-hat-das-mit-energieforschung-zu-tun/).<br>

Brückmann, G. (2022). *The effects of policies providing information and trialling on the knowledge about and the intention to adopt new energy technologies*. Energy Policy, 167, [doi.org/10.1016/j.enpol.2022.113047](https://doi.org/10.1016/j.enpol.2022.113047) <br>

Brückmann, G. (2022). *Test drives & information might not boost actual battery electric vehicle uptake*. Transportation Research Part A: Policy and Practice, 160, [doi.org/10.1016/J.TRA.2022.03.025](https://doi.org/10.1016/J.TRA.2022.03.025) <br>

Wicki, M., Brückmann, G. & Bernauer, T. (2022). *How to accelerate the uptake of electric cars? Insights from a choice experiment*. Journal of Cleaner Production, [doi.org/10.1016/j.jclepro.2022.131774](https://doi.org/10.1016/j.jclepro.2022.131774) <br>

Wicki, M., Brückmann, G., Quoß, F. & Bernauer, T. (2022). *What do we really know about the acceptance of battery electric vehicles? – Turns out, not much*. Transport Reviews, [doi.org/10.1080/01441647.2021.2023693](https://doi.org/10.1080/01441647.2021.2023693) <br>

Brückmann, G., Wicki, M. & Bernauer, T. (2021). *Is resale anxiety an obstacle to electric vehicle adoption? Results from a survey experiment in Switzerland*. Environmental Research Letters, 16 (12), 124027. [doi.org/10.1088/1748-9326/ac3531](https://doi.org/10.1088/1748-9326/ac3531) <br>

Brückmann, G., Willibald, F. & Blanco, V. (2021). *Battery Electric Vehicle adoption in regions without strong policies*. Transportation Research Part D: Transport and Environment, 90, 102615. [doi.org/10.1016/J.TRD.2020.102615](https://doi.org/10.1016/J.TRD.2020.102615) <br>

Brückmann, G. & Bernauer, T. (2020). *What drives public support for policies to enhance electric vehicle adoption?* Environmental Research Letters, 15(9), 094002. [doi.org/10.1088/1748-9326/ab90a5](https://doi.org/10.1088/1748-9326/ab90a5) <br> • Covered in [Yale Environmental Review](https://environment-review.yale.edu/pulling-public-embrace-adoption-electric-vehicles). Explained in [ISTP4Public video](https://twitter.com/istp_eth/status/1271004682979336193?s=20). <br><br>

::: {.callout-tip collapse="false"}
#### Other types of work:
```{=html}
<p>
For other types of publications, such as my PhD thesis, please refer to my CV.<a href="https://brueckmann.github.io/cv.html">CV</a>.
</p>
```
:::