---
title: "Academic Teaching Experience"
format: html
---

## 🧑🏼‍🏫 Current Courses at the University of Bern

-   **Master Seminar** *Energy and Mobility Policies for Decarbonisation*, University of Bern *(Fall 2022,2023,2024 & 2025)* <br>
    -   Access the most-recent [syllabus online](https://github.com/brueckmann/Syllabus_PolDec_HS2025/blob/main/PDF_Syllabus_PolDec_GBrueckmann.pdf?raw=True)
-   **Lecture** *The Art of Causal Inference*, University of Bern *(Spring 2024)* <br>
    -   Access the most-recent [syllabus online](https://brueckmann.github.io/KKI_Syllabus/PDF_Syllabus_KKI_GBrueckmann.pdf?raw=True)


## 📚 Co-teaching, Shorter Teaching, Guest lectures & Thesis Supervision

-   **Lectures** *Renewable Energy Acceptance using Causality and Data Science* Organiser: Prof. Dr. Philipp Schütz, Domain Experience: Data analytics for energy systems and IOT, Lucerne University of Applied Sciences and Arts. *(Spring 2024)*<br>
-   **Lectures** *Political Economy of Climate Change*, Organiser: Prof. Dr. V. Koubi, University of Bern *(Spring 2023)*<br>
-   **Lecture** *Climate Change Policy and Electric Vehicles in Europe*, Organiser: Climate Physics seminar, Weber State University, Ogden, Utah. *(Nov 2022)*<br>
-   **Supervision** of *master thesis* entiteled "Electric charging behaviour – Understanding the trilemma of willingness to pay, the value of time and source of energy in the context of public charging stations in the German part of Switzerland", ETH Zürich *(Nov 2021)*<br>
-   **Lecture** on *Battery-electric Vehicle Adoption* at Frontiers in Energy Research, Organiser: Energy Science Centre, ETH Zurich *(2021)*<br>
-   **Lecture** on *Sustainable Development* at “Political Economy”. Organisation jointly with: V. Koubi, D. Kolcava, ETH Zurich *(2021)*<br>
-   **Supervision** of *master thesis* entiteled “The role of charging infrastructure to the mainstream adoption of battery electric vehicles (BEVs)”, ETH Zurich *(2020)*<br>
-   **Lecture** on *Experimental Political Science* at Proseminar 2. Organisers: D. Presberger, F. Quoß, ETH Zurich *(2020)*<br>
-   **Tutorial** *Methoden der Empirischen Sozialforschung* (Empirical social science methods), lecture by Dr. L. Rudolph, ETH Zurich *(2018&2019)*<br>
-   **Seminar** instructor *IDEA League Challenge: The mobility challenge*, Organize: Prof. Dr. T. Bernauer, ETH Zurich *(2018&2019)*<br>
-   **Tutorial** *Mathematical Methods in Economics*, accompanying lecture by Prof. H. Rainer, Ph.D., LMU Munich *(2012)* <br>

